management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 8080
  endpoint:
    health:
      show-components: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "* "

info:
  app:
    name: hello-actuator
    company: si

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true

